### ISSUE TITLE
script export error

### ISSUE THREAD

**Issue by shun9092** [thesupersonic16/DALTools#21]
I tried to export script.pck file to *.csv

But it doesn't work

SDE Info:
    Version: 1.0.1
    Args: 
    StartDir: E:\Program Files (x86)\Steam\steamapps\common\DATE A LIVE Rio Reincarnation\Kor\DALTools1.11.4\
    Process Level: User
    ScriptPath: E:\Program Files (x86)\Steam\steamapps\common\DATE A LIVE Rio Reincarnation\Data/JPN/Script/Script.pck

Exception:
    Type: ArgumentOutOfRangeException
    Message: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Source: mscorlib
    Function: Void ThrowArgumentOutOfRangeException(System.ExceptionArgument, System.ExceptionResource)
    StackTrace: 
       at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
       at DALLib.Scripting.STSCInstructions.Instruction.GetArgument[T](Int32 index)
       at DALLib.ImportExport.TranslationSTSCHandler.ExportTranslation(Int32 fileTypeIndex, STSCFile script, STSCFileDatabase database)
       at ScriptDialogueEditor.MainWindow.ExportTranslationMenuItem_Click(Object sender, RoutedEventArgs e)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
       at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.DispatcherOperation.InvokeImpl()
       at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
       at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Windows.Threading.DispatcherOperation.Invoke()
       at System.Windows.Threading.Dispatcher.ProcessQueue()
       at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at System.Windows.Application.Run(Window window)
       at ScriptDialogueEditor.App.Main(String[] args)
    InnerException: 

This file already finished translate
https://drive.google.com/file/d/1XshrToEGcdb0b8f9BjNgUW2ntMYkkwwT/view?usp=sharing

Would you please check this error?

**Comment by thesupersonic16** [comment]
Fixed in cb200ad88b2166ec72bb6e13424c1e058b232787, please let me know if this solves the issue or not.

[DALTools.zip](https://github.com/thesupersonic16/DALTools/files/5144716/DALTools.zip)

**Comment by shun9092** [comment]
Extract is working but Import is come out error

SDE Info:
    Version: 1.0.1
    Args: 
    StartDir: E:\Program Files (x86)\Steam\steamapps\common\DATE A LIVE Rio Reincarnation\Kor\DALTools_fix\
    Process Level: User
    ScriptPath: E:\Program Files (x86)\Steam\steamapps\common\DATE A LIVE Rio Reincarnation\Kor\DALTools_fix\k\Script.pck

Exception:
    Type: IOException
    Message: The process cannot access the file 'E:\Program Files (x86)\Steam\steamapps\common\DATE A LIVE Rio Reincarnation\Kor\DALTools_fix\1st\0_debug_11.csv' because it is being used by another process.
    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
       at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
       at System.IO.File.ReadAllText(String path)
       at ScriptDialogueEditor.MainWindow.ImportTranslationMenuItem_Click(Object sender, RoutedEventArgs e)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
       at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.DispatcherOperation.InvokeImpl()
       at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
       at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Windows.Threading.DispatcherOperation.Invoke()
       at System.Windows.Threading.Dispatcher.ProcessQueue()
       at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at System.Windows.Application.Run(Window window)
       at ScriptDialogueEditor.App.Main(String[] args)
    InnerException:

**Comment by thesupersonic16** [comment]
Not sure if I can fix that. I might beable to make it show an error message instead of a crash.

You using Excel? If you are you need to close the program to allow the file to be used.

**Comment by shun9092** [comment]
It just work "batch" import translation or without key

But it doesn't work import translation or without key

Weird

**Comment by thesupersonic16** [comment]
This might help fix the issue. Can you check? 

[DALTools.zip](https://github.com/thesupersonic16/DALTools/files/5144781/DALTools.zip)

**Comment by shun9092** [comment]
Good, it seems to work fine.

Both work.

**Comment by thesupersonic16** [comment]
Cool. I will close this issue after I submit the release.

**Comment by thesupersonic16** [comment]
Published! Feel free to reopen if you got any relevant issues. Closing
