### ISSUE TITLE
PSVita database and script opening fatal error

### ISSUE THREAD

**Issue by andru9592** [thesupersonic16/DALTools#22]
Hello! I'm trying to open the database file and script file from ps vita date-a-live, but I get an error. Pls help!

SDE Info:
```
    Version: 1.12.0
    Args: 
    StartDir: F:\DALTools v2\
    Process Level: User
    GamePath: 
    DataBasePath: F:\DALTools v2\database.bin
```

Exception:
```
    Type: STSCDisassembleException
    Message: Failed to disassemble the script file . Got opcode 0xD4 at 0x0000003C in "" There is no opcodes larger than 0x93!
    Source: DALLib
    Function: Void Load(DALLib.IO.ExtendedBinaryReader, Boolean)
    StackTrace: 
       at DALLib.File.STSCFile.Load(ExtendedBinaryReader reader, Boolean keepOpen)
       at DALLib.File.STSCFileDatabase.Load(ExtendedBinaryReader fileReader, Boolean keepOpen)
       at DALLib.File.FileBase.Load(Stream stream, Boolean autoDecompress, Boolean keepOpen)
       at DALLib.File.FileBase.Load(String path, Boolean keepOpen)
       at ScriptDatabaseEditor.MainWindow.ChangeDatabase(String path)
       at ScriptDatabaseEditor.MainWindow.LoadButton_Click(Object sender, RoutedEventArgs e)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
       at System.Windows.Controls.Primitives.ButtonBase.OnClick()
       at System.Windows.Controls.Button.OnClick()
       at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
       at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
       at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
       at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
       at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
       at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
       at System.Windows.Input.InputManager.ProcessStagingArea()
       at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
       at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
       at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
       at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at System.Windows.Application.Run(Window window)
       at ScriptDatabaseEditor.App.Main(String[] args)
    InnerException: 
```

**Comment by thesupersonic16** [comment]
The database editor is actually only meant to work for the RR remake which the Vita version might have different code. Can you send the Script folder and if possible a decrypted eboot file so I can take a look to see if they are similar?

**Comment by andru9592** [comment]
https://drive.google.com/drive/folders/1Bt6PhBZQdx3hTgFkyoIrosQPvfP4qXqR?usp=sharing

**Comment by thesupersonic16** [comment]
Does the PS Vita version of the game include artbooks and Drama CDs?

**Comment by andru9592** [comment]
No, it doesn't.

**Comment by thesupersonic16** [comment]
Try this and let me know if it works or not.

[Release.zip](https://github.com/thesupersonic16/DALTools/files/5824280/Release.zip)

**Comment by andru9592** [comment]
DatabaseEditor opens and saves the file, thank you. But DialogueEditor couldn't save the file =(

SDE Info:
```
    Version: 1.0.2
    Args: 
    StartDir: F:\DALTools3\
    Process Level: User
    ScriptPath: F:\release_win64_7\PCSG00599_decrypted_new\Script\Script.pck
```

Exception:
```
    Type: ArgumentNullException
    Message: String reference not set to an instance of a String.
Parameter name: s
    Source: mscorlib
    Function: Byte[] GetBytes(System.String)
    StackTrace: 
       at System.Text.Encoding.GetBytes(String s)
       at DALLib.File.STSCFile.Save(ExtendedBinaryWriter writer)
       at ScriptDialogueEditor.STSCFileDialogue.Save(ExtendedBinaryWriter writer)
       at DALLib.File.FileBase.Save(Stream stream)
       at ScriptDialogueEditor.MainWindow.SaveScript()
       at ScriptDialogueEditor.MainWindow.SaveButton_Click(Object sender, RoutedEventArgs e)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
       at System.Windows.Controls.Primitives.ButtonBase.OnClick()
       at System.Windows.Controls.Button.OnClick()
       at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
       at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
       at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
       at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
       at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
       at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
       at System.Windows.Input.InputManager.ProcessStagingArea()
       at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
       at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
       at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
       at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at System.Windows.Application.Run(Window window)
       at ScriptDialogueEditor.App.Main(String[] args)
    InnerException: 
```

**Comment by andru9592** [comment]
I also used an English translated script file from reddit, and it worked well. Maybe the Japanese script file is not saved due to system restrictions?

**Comment by thesupersonic16** [comment]
There shouldn't be any system restrictions, Pretty sure its an error on my end. Try this. The file size seems to change when saved so I'm not sure if that will effect how the game will load the files.

[Release.zip](https://github.com/thesupersonic16/DALTools/files/5824329/Release.zip)

**Comment by andru9592** [comment]
The file is saved successfully. But when I try to run it on the device, error c2-12828-1 appears.
![2021-01-16-150729](https://user-images.githubusercontent.com/46836785/104811665-32ccc880-580e-11eb-93f3-53f97f151a77.jpg)

**Comment by thesupersonic16** [comment]
Does both of the files cause the error? Or does one of the two cause it? Like does any of the two files alone work or not.

**Comment by andru9592** [comment]
When I changed the database file, there is no change in the game, but it runs. When I change the script file, the game doesn't start and gets an error.

**Comment by thesupersonic16** [comment]
I guess we will look at the database issue later and first get the Script pck working. Does this at least get the game running?

[Release.zip](https://github.com/thesupersonic16/DALTools/files/5824381/Release.zip)

**Comment by andru9592** [comment]
Sorry, changing the database file works)
![2021-01-16-154053](https://user-images.githubusercontent.com/46836785/104812177-8db3ef00-5811-11eb-9fec-7fd9cfe23c23.jpg)

**Comment by andru9592** [comment]
Oh, it works! Thank you very much!
![2021-01-16-154502](https://user-images.githubusercontent.com/46836785/104812234-f4d1a380-5811-11eb-837a-8314e3f4cfbe.jpg)

**Comment by thesupersonic16** [comment]
Great! Please let me know if you encounter any more issues by reopening this issue with a new comment.

if you need to repack the .pck files manually using PCKTool, make sure to add -s in the command line.

**Comment by andru9592** [comment]
Another problem. FontEditor crashes when opening font files. I added these files to Google Drive. Please see what you can do.

**Comment by andru9592** [comment]
Also, textool seems to pack the file incorrectly. After packaging, it is no longer unpacked. I also added an example tex file to Google Drive.

**Comment by thesupersonic16** [comment]
FontEditor is kinda useless on the PC version, not sure if it works for the PSV but I updated it while at it.
As for TEXTool, I made some changes which might fix your issue.

Let me know if it all works or not.

[Release.zip](https://github.com/thesupersonic16/DALTools/files/5825713/Release.zip)

**Comment by andru9592** [comment]
textool now packs files successfully, but on vita it doesn't work - black screen.

**Comment by thesupersonic16** [comment]
Do you know how to use a hex editor? If you do I would like to know what would happen with a quick change.

**Comment by andru9592** [comment]
I know how to use hex editor a little)

**Comment by thesupersonic16** [comment]
Open your new .tex file and at 0x0F where it should say `01` Change it to `81` then save and let me know if the file loads.

**Comment by andru9592** [comment]
Did I do it right?
![Безымянный](https://user-images.githubusercontent.com/46836785/104839434-2ca02000-58d2-11eb-844f-5436901b94f0.png)

**Comment by thesupersonic16** [comment]
Yeah like that. Save it and let me know if the file loads this time.

**Comment by andru9592** [comment]
So, it doesn't work.

**Comment by thesupersonic16** [comment]
Does editing title.tex work? (both repacking it and editing the 01 to 08)

**Comment by thesupersonic16** [comment]
Actually it might be an alignment issue. Try this. (no need to hex edit with this version)

[Release.zip](https://github.com/thesupersonic16/DALTools/files/5825994/Release.zip)

**Comment by andru9592** [comment]
I went back to the title.tex file, edited it, and tried running it again. It didn't work. I uploaded the edited file to Google Drive, maybe I'm doing something wrong?

**Comment by thesupersonic16** [comment]
Just wait a little. I'm checking the differences with the PC and the PSV. I'll send another release soon.

**Comment by thesupersonic16** [comment]
Try this.

[Release.zip](https://github.com/thesupersonic16/DALTools/files/5826037/Release.zip)

**Comment by andru9592** [comment]
Unfortunately, it didn't work.

**Comment by thesupersonic16** [comment]
You could also try enabling compression. Make sure you are using the newest zip I sent and open the .xml file for the texture and scroll down until you see this
```xml
<Compress>false</Compress>
```
Change the `false` to `true` like
```xml
<Compress>true</Compress>
```
Then save and drag the xml file into TEXTool.

**Comment by andru9592** [comment]
Yes, it worked! Thanks!

**Comment by thesupersonic16** [comment]
Oh. Never seen a game that uses .tex that required compression. Well let me know if you see any more issues. I might keep this issue open for a while just in case.

**Comment by thesupersonic16** [comment]
Closing due to inactivity. Please reopen the issue if you have any issues.
