### ISSUE TITLE
More Sting game support?

### ISSUE THREAD

**Issue by otomevn** [thesupersonic16/DALTools#23]
Hello, first I want to thank you for making this tool. We're translating another Sting game, they used the same file type but when I loaded it, the program immediately crashed.

The game's name is Psychedelica of the Black Butterfly. [Here](https://cdn.discordapp.com/attachments/452432163514875904/809280044048318464/Psychedelica_of_the_black_butterfly_ENG.7z) are its data files, including database file and script.pck file. I really appreciate it if you can take a look at it when you're free.

Thank you so much in advance!

**Comment by thesupersonic16** [comment]
This repository is intended for only Date A Live games. I can try support that game aswell but that will depend on how similar the game is from Date A Live.

Also the instructions look different from DAL: RR. I will need the exe file of the game to look into to see if the names are in.

**Comment by otomevn** [comment]
Thank you very much for the quick reply! I understand that this is very hard and time-consuming, it's perfectly okay if ultimately, you couldn't help me.

I see, thank you! If I'm not mistaken, **[here](https://cdn.discordapp.com/attachments/809280505308119040/809356568138612736/psychedelica_exe.7z)** is the .exe file.

**Comment by thesupersonic16** [comment]
Can I see what the settings and extra menus look like?

**Comment by otomevn** [comment]
Okay, here are some screenshots:
Menu: [here](https://cdn.discordapp.com/attachments/809280505308119040/809699310207107072/Screen_Shot_02-12-21_at_03.15_PM_001.PNG) 

Options:
[here](https://cdn.discordapp.com/attachments/809280505308119040/809699312132292638/Screen_Shot_02-12-21_at_03.15_PM.PNG)

Extras menu:
[here](https://cdn.discordapp.com/attachments/809280505308119040/809698994862948372/Screen_Shot_02-12-21_at_03.14_PM.PNG)

Flow chart:
[here](https://cdn.discordapp.com/attachments/809280505308119040/809698989443776552/Screen_Shot_02-12-21_at_03.14_PM_001.PNG)

Thank you so much! If you need anything else please tell me.

**Comment by thesupersonic16** [comment]
Can you check if the game still works with this file and also says a bunch of "Test" on two lines on the first dialogue. If it works, can you also take screenshot and send it here?.

[a](https://cdn.discordapp.com/attachments/809707575276601344/809707595849531392/Script.pck)

**Comment by otomevn** [comment]
Thank you! Work like a charm!
[Here](https://cdn.discordapp.com/attachments/809280505308119040/809711279966912542/unknown.png) is the screenshot.

**Comment by thesupersonic16** [comment]
Got all the scripts to read with no errors, but I need the application tested with the actual game.

If you don't mind, can you try mess with this and let me know of any issues or anything missing? Also make sure to backup any text often just incase a random crash were to happen.

Right now this should only allow just message editing, which means language settings, database and exporting/importing don't work. To get the application loaded you need to give it an extra argument of `pbb`. 
Here is example: `ScriptDialogueEditor.exe Data\ENG\Script\Script.pck pbb` 

If you need any help with using the application, feel free to send a message.

[ScriptDialogueEditor.zip](https://cdn.discordapp.com/attachments/809707575276601344/809747464147828786/ScriptDialogueEditor.zip)

**Comment by otomevn** [comment]
Oh thank you so much! That was fast xD

I got the application loaded with all the scripts with no problems. But I'm a little confused about "messing with it". Do I just need to randomly change the texts everywhere and then load the game up, test if the texts are displayed correctly? Or do I need to do something else?

I'm also not sure about backing up the texts. Is there any way to export them to texts file and import back? Or do we just click save?

Once again thank you very much for your time, I really appreciate it!

**Comment by thesupersonic16** [comment]
Just use it like normal and let me know if there is something that is broken or something is missing that you need to edit.
Just select a script on the left and double click on the text on the right to change it and then press save and load up your game.

As for exporting to text file, It's currently broken, but I can try get it working later.

**Comment by otomevn** [comment]
Okay, thanks! I will test the application and let you know soon!

**Comment by thesupersonic16** [comment]
Here is what one of the export/import formats look like. Is there any requirements you have for them? I don't do translating so I don't really know.

TSV (In VSCode Preview):
<img width="594" alt="Code_2021-02-13_01-16-02" src="https://user-images.githubusercontent.com/25761885/107779154-15e9cd80-6d99-11eb-8d0c-1273f2b53b15.png">

**Comment by otomevn** [comment]
It looks super neat! Thank you!

Normally we work as a team on a google sheet ([it looks like this](https://cdn.discordapp.com/attachments/496635393425539072/809812599528488990/unknown.png) and [this](https://cdn.discordapp.com/attachments/496635393425539072/809812756281950258/unknown.png)), and I find this method is extremely effective. We would see everyone's edits in real-time and we would have control over everything (like knowing when a translator is inactive for a long period of time, or knowing when a person used machine translators). We've completed 6 long visual novel projects in merely 2.5 years by using this method. 

In the past, we would give some scripts to someone and then they would disappear for like half a year without any prior notice, and we'd stuck waiting for that person. Using a google sheet, we wouldn't have that problem anymore. So I would love it if you can support xlxs export/importing - which is excel's native format.

I totally understand if you couldn't tho and I appreciate all of your help! Thanks a lot!!!

**Comment by thesupersonic16** [comment]
oh that's interesting, happy to hear more. Also I think Google Sheets can actually import .tsv files so I might not need to add xlxs.

I'll send you a build with what DALTools normally outputs, but if there is anything else that you want/need changed, please let me know.
To export just right click any script and click "Batch Export Translation" and when importing use the "(Without Key)" option. I notice the flaw pretty late with the other option. lol

I hope this all will help smooth out your translation workload.

[ScriptDialogueEditor.zip](https://cdn.discordapp.com/attachments/809707575276601344/809818785666170981/ScriptDialogueEditor.zip)

**Comment by thesupersonic16** [comment]
Oh exporting everything into a single xlsx wasn't that hard. Thats over 100 sheets lol
<img src="https://cdn.discordapp.com/attachments/809707575276601344/809836925413621780/unknown.png">

**Comment by otomevn** [comment]
Oh importing tsv files would be nice. But there are over 100 scripts so I guess we will have to manually upload them into a google spreadsheet?

 > Oh exporting everything into a single xlsx wasn't that hard. That's over 100 sheets lol

Oooh cool, but I think Google sheets wouldn't load an xlxs file when there are over 100 sheets, due to number of cells limit exceeded. But in the worst case I think we could just manually import those.

I encountered a new problem tho >"< sorry for bothering you again, but do you have any idea why would my edited font doesn't work? I tried to add Vietnamese characters to it but when I boot the game up and test, the newly fixed characters don't appear.

[Here](https://cdn.discordapp.com/attachments/809280505308119040/809871003060273152/Psychedelica_test.7z) is the edited font & script.pck file.
Here is the scripts I tested with

àáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩò
óọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđ
ÀÁẠẢÃÂẦẤẬẨẪĂẰẮẶẲẴÈÉẸẺẼÊỀẾỆỂỄÌÍỊỈĨÒ

ÓỌỎÕÔỒỐỘỔỖƠỜỚỢ
ỞỠÙÚỤỦŨƯỪỨỰỬỮỲÝỴỶỸĐ

Only ứ ừ ữ etc... showed up. I have no idea why tho. Thank you again for your time! You're too kind!

**Comment by thesupersonic16** [comment]
I knew this was going to happen. Did the original font have all the characters you needed? I think this is the same issue with Date A Live where they hardcoded a range of characters that can be read. I could try check it out, but I didn't have much luck with DAL.

**Comment by otomevn** [comment]
Oh, I see, in that case, I guess the only choice is to use a character replacing table. The tool could use a feature that allows it to apply a table when exporting the translation. But that means more work for you >"<

**Comment by thesupersonic16** [comment]
Like I said I didn't have much luck with DAL, but I have still made an attempt which might work or might not work. The exe linked should have 3 byte conversion disabled, this trick has worked for one language in the past.
Let me know if it fixes or breaks anything.

[Psychedelica_of_the_Black_Butterfly.exe](https://cdn.discordapp.com/attachments/809707575276601344/810033794525954048/Psychedelica_of_the_Black_Butterfly.exe)

**Comment by otomevn** [comment]
I see, thank you!
Unfortunately, the new exe file crashed after I clicked new game, chose heroine's name and clicked OK.

**Comment by thesupersonic16** [comment]
I did some calculating, I got the patch wrong and there shouldn't be anything thing prevent it from working. Looks like we will need the character replacing table. Is there any standard formats out there?

**Comment by otomevn** [comment]
Thank you! 
We've been using a table formatted like this:
[Screenshot](https://user-images.githubusercontent.com/73972587/107866628-677f7e80-6ea5-11eb-8aed-338106a8546a.jpg)
Character1=character2
Character1 is from our Vietnamese alphabet, and it's replaced by character2 (character2 is what available in the font). Then we edit the font texture.

**Comment by thesupersonic16** [comment]
Kinda rushed this, Is this what you need?

Just make a text file called `replace.ini` next to `Script.pck` and place your replacements like how you have it written in the screenshot. It should show the replacements for all the messages within the app and export/imports except the "Prev Message" part when editing within the app.

[ScriptDialogueEditor.zip](https://cdn.discordapp.com/attachments/809707575276601344/810347712553680916/ScriptDialogueEditor.zip)

**Comment by otomevn** [comment]
THANK YOU SO MUCH!!!
That's exactly what I need. I've tried changing a few characters and it works flawlessly in-game. I will test more to see if it has any error. 

Once again, thank you for your time! And your kindness. You're an angel!!!

**Comment by otomevn** [comment]
Sorry for bothering you again, I added the full table then the application crashed.
[Here](https://cdn.discordapp.com/attachments/809280505308119040/810431562855481385/replace.ini)is my table. Dunno what went wrong T_T

**Comment by thesupersonic16** [comment]
Did any error message show up?

**Comment by otomevn** [comment]
Yes, [here](https://cdn.discordapp.com/attachments/809280505308119040/810442057902325780/unknown.png) it is.

**Comment by thesupersonic16** [comment]
I guessed right. I might add a check later, but check if you have any duplicates in the file. You cannot have any duplicates with other lines on the left side of the = symbol.

**Comment by otomevn** [comment]
Oh, I see, that's a typo on my part, found and fixed it xD THANK YOU SO MUCH! It worked flawlessly!!!
By the way, happy valentine! xD

**Comment by otomevn** [comment]
Hello,

I'm here to bother you again >"<
I imported .tsv files manually into google sheets. Then I translated some lines, download [the sheet](https://cdn.discordapp.com/attachments/809280505308119040/810745672739455006/Psychedelica_of_the_black_butterfly_Steam_v1.0_1.xlsx) as xlsx, begged a friend to write a tool to split the xlsx into tsv. Then I tried to batch import the newly split tsv into the tool to repack but got **[this](https://cdn.discordapp.com/attachments/809280505308119040/810745030284804116/Screen_Shot_02-15-21_at_12.28_PM.PNG)** error. 

As far as I know, the tsv files aren't being used by any program. Any ideas? Thanks a lot in advance!

**Comment by thesupersonic16** [comment]
The TSV is invalid. I look into trying to import the xlsx.

**Comment by thesupersonic16** [comment]
Haven't tested it, but give this build a try. It adds an extra option for xlsx importing.
[ScriptDialogueEditor.zip](https://cdn.discordapp.com/attachments/809707575276601344/810756188765421568/ScriptDialogueEditor.zip)

**Comment by otomevn** [comment]
BRILLIANT! Thanks a lot, I'm so grateful.
I've tested it and it worked flawlessly. Honestly, I can't thank you enough >"<

**Comment by otomevn** [comment]
Hello, it's me again! The translation team began to work and everything seems perfect. Except for one issue, we can't edit the speaker's name. Is there any way to edit it or the tool isn't supporting it yet?
Thank you!

**Comment by thesupersonic16** [comment]
It might be possible. I will try look into getting it exported. Is it possible to have 2 names show up?

**Comment by thesupersonic16** [comment]
Just added `Name` as a separate entry. I'm not 100% sure how they work as I don't have the game. Let me know if this helps.

[ScriptDialogueEditor.zip](https://cdn.discordapp.com/attachments/809707575276601344/812165051191525406/ScriptDialogueEditor.zip)

**Comment by Kent9595** [comment]
Hello, I am a member of the Otomevn group. I just did a test with the new tool, and I can only modify the name inside, it still keep the English name when importing xlsx file. Is there any way to change the Name in the script by the Name that has been modified in an xlsx file?
Thank you for advance.

**Comment by thesupersonic16** [comment]
Can I see a screenshot of the game and the same text in the editor? I could be changing the wrong thing.

**Comment by thesupersonic16** [comment]
I'm unclear wit hwhat you are saying, can you explain what you mean by the modifying the name inside? Are you editing the name on the Name entry? Maybe I can make it read the name from the Message entry instead if its confusing.

**Comment by Kent9595** [comment]
Hello.

 Here is the image in the game: ![Game](https://cdn.discordapp.com/attachments/809280505308119040/812325435190280232/Anh_chup_man_hinh_19.png).

The same line in the editor:  ![Editor](https://cdn.discordapp.com/attachments/809280505308119040/812325398305308712/Anh_chup_man_hinh_20.png). 
If I click here, I can change the Name "Me".

The same line in the Xlsx file  ![Xlsx](https://cdn.discordapp.com/attachments/809280505308119040/812325364319649842/Anh_chup_man_hinh_21.png).

In the Xlsx file I modified the Name "I" => "Tôi", but when I import the XLsx file into the Editor, the Name still keeps the English name. And I would like that if I change the name in the XLSX file, the one in the Editor changes too. 
Please tell me if you don't understand what I want to say. I’m sorry for the inconvenience.
Thank you for advance.

**Comment by thesupersonic16** [comment]
Ok I see. I intended for the file to be re-exported. I will look into getting it to import from the Comment column instead. Will take some time as the library isn't designed to read from there. Don't do any exporting with that build.

**Comment by Kent9595** [comment]
Thank you very much and sorry to bother you.

**Comment by thesupersonic16** [comment]
I actually just notice the build before had another import issue, hopefully this change will also fix that issue. This should now import the names from the same row as the message. Haven't tested it much, but let me know if you run into anymore issues.

[ScriptDialogueEditor.zip](https://cdn.discordapp.com/attachments/809707575276601344/812335375686172672/ScriptDialogueEditor.zip)

**Comment by Kent9595** [comment]
Okay. I'll try it. Thank you very much.

**Comment by Kent9595** [comment]
That works. 

![ảnh](https://cdn.discordapp.com/attachments/809280505308119040/812354568066433084/unknown.png)

Thank you very much.

**Comment by ToumaKun** [comment]
Hello, @thesupersonic16!
I have a couple of questions for you.
Can you tell me your mail?
If you don't want anyone to know her, you can write to [mine](touma@jmusic.in).

**Comment by thesupersonic16** [comment]
I would prefer to reply on GitHub. What questions do you have?

**Comment by ToumaKun** [comment]
> I would prefer to reply on GitHub. What questions do you have?

This is not a public question, and I would not like anyone to know:)

**Comment by thesupersonic16** [comment]
Then message me on Discord at `SuperSonic16#0001`

**Comment by ToumaKun** [comment]
I sent a friend request :)

**Comment by thesupersonic16** [comment]
I do not accept friend requests. Just send me a DM directly.

**Comment by ToumaKun** [comment]
I cannot write to you until you accept as friends(
![image](https://user-images.githubusercontent.com/88413286/128111195-35d2f620-8207-4143-a694-8cc28ab59b67.png)

**Comment by thesupersonic16** [comment]
Then send me a message on Twitter, my DMs are open there.

**Comment by ToumaKun** [comment]
> Then send me a message on Twitter, my DMs are open there.

Done

**Comment by Cosetto** [comment]
@thesupersonic16 Hey there, I wonder if you can add support for this fnl font?
[Font.zip](https://github.com/thesupersonic16/DALTools/files/15024542/Font.zip)

**Comment by thesupersonic16** [comment]
@Cosetto What game is those files from?

**Comment by thesupersonic16** [comment]
Just pushed some code to handle the file. I have not tested the code. You can download it [here](https://github.com/thesupersonic16/DALTools/actions/runs/8808901918/artifacts/1441447155).

To load the file, just open the .fnt file, not the .pck file.

**Comment by Cosetto** [comment]
> @Cosetto What game is those files from?

It's [this one](https://store.steampowered.com/app/2432110/WHITE_ALBUM_Memories_like_Falling_Snow/)
So there are some questions I would like to ask. Firstly, when I opened the font and made no changes before saving, it resulted in a file which is only 27kb. The same problem when modifying the font then saving.
[en25px0.zip](https://github.com/thesupersonic16/DALTools/files/15085172/en25px0.zip)
Is there something wrong?
Secondly, when I added new characters, how do I draw new bitmap for them?
![image](https://github.com/thesupersonic16/DALTools/assets/81801486/71daaa2d-3cc0-4295-a109-7b527e6b2305)

**Comment by thesupersonic16** [comment]
> > @Cosetto What game is those files from?
> 
> It's [this one](https://store.steampowered.com/app/2432110/WHITE_ALBUM_Memories_like_Falling_Snow/) So there are some questions I would like to ask. Firstly, when I opened the font and made no changes before saving, it resulted in a file which is only 27kb. The same problem when modifying the font then saving. [en25px0.zip](https://github.com/thesupersonic16/DALTools/files/15085172/en25px0.zip) Is there something wrong? Secondly, when I added new characters, how do I draw new bitmap for them? ![image](https://private-user-images.githubusercontent.com/81801486/325049501-71daaa2d-3cc0-4295-a109-7b527e6b2305.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDY1NjIsIm5iZiI6MTcxMzk0NjI2MiwicGF0aCI6Ii84MTgwMTQ4Ni8zMjUwNDk1MDEtNzFkYWFhMmQtM2NjMC00Mjk1LWExMDktN2I1MjdlNmIyMzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA4MTEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmNGM0YWVhOGU1Zjk0ODUzOTQ1NDNiNDU1YjljNjZhNTIyMzYwY2RjMDA2ODgzZTNmYmJhNDFkODBjZjliM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VPj-Xgk_qA0DjghJc5rj6nSW23qNtNGE6yvPCN335pI)

Might be easier to reuse one of the unused characters. As for drawing, thats a good point, I never made a way to extract and load custom textures.

Can you check if the game accepts the edited font file?

**Comment by thesupersonic16** [comment]
Just realised I never wrote the function to save the file. so ignore the last part I said.

**Comment by Cosetto** [comment]
Hm, [this one](https://github.com/marcussacana/AquaPlusEditor/blob/master/AquaPlusEditor/FNT.cs) can draw new bitmap I think, but it doesn't support the game.

**Comment by thesupersonic16** [comment]
Added some importin, exporting and saving code. Let me know how it goes. 

[Download](https://github.com/thesupersonic16/DALTools/actions/runs/8813920260/artifacts/1442564740)

**Comment by thesupersonic16** [comment]
You will need to export the texture and make the edits using any image editing tool, then reimport the png.

I believe by default DALLib saves textures in PNG format which not all games support.

**Comment by Cosetto** [comment]
My game crashed, and the problem was when importing the texture back. Looks like the game doesn't support png?

**Comment by thesupersonic16** [comment]
I was wrong about it using PNG, however it did save without the magic. I have enabled it for the files below, can you check if they load in game?

[Font.zip](https://github.com/thesupersonic16/DALTools/files/15092314/Font.zip)

**Comment by Cosetto** [comment]
![image](https://github.com/thesupersonic16/DALTools/assets/81801486/4f3cd76a-5d70-4bf7-ab0b-004d8e69fe5e)
Yup, it works, but it looks kinda weird

**Comment by thesupersonic16** [comment]
Thats expected since I used a gradient in the texture. You can download the updated build [here](https://github.com/thesupersonic16/DALTools/actions/runs/8814825772/artifacts/1442755654).

**Comment by Cosetto** [comment]
![image](https://github.com/thesupersonic16/DALTools/assets/81801486/53c0b9b6-cc76-4c32-bdb2-a8944f77915c)
It works like a charm. Thank you very much!

**Comment by Cosetto** [comment]
> Thats expected since I used a gradient in the texture. You can download the updated build [here](https://github.com/thesupersonic16/DALTools/actions/runs/8814825772/artifacts/1442755654).

Hey there, sorry for bothering again. If it's possible,  you could add an option to generate characters_list.txt of the font?

**Comment by thesupersonic16** [comment]
> Hi, sorry to bother you, but do you still have this build?
> My buddies and I are planning to try to translate this game too.

Psychedelica of the Black Butterfly?

**Comment by Gertram** [comment]
> > Hi, sorry to bother you, but do you still have this build?
> > My buddies and I are planning to try to translate this game too.
> 
> Psychedelica of the Black Butterfly?

Yes

**Comment by thesupersonic16** [comment]
I believe this should work.

[STSCTool.zip](https://github.com/user-attachments/files/18408662/STSCTool.zip)

**Comment by Gertram** [comment]
> I believe this should work.
> 
> [STSCTool.zip](https://github.com/user-attachments/files/18408662/STSCTool.zip)
IT'S WORK!
Thank you so much! You’re a lifesaver!

**Comment by Linsey2244** [comment]
> I believe this should work.
> 
> [STSCTool.zip](https://github.com/user-attachments/files/18408662/STSCTool.zip)

![Image](https://github.com/user-attachments/assets/659316a0-5217-4b0f-8213-40e32924c275)
![Image](https://github.com/user-attachments/assets/b62b0693-7397-4196-ac9d-770dd9a07704)

Hi, sorry to bother you, I'm also trying to translate Pyschedelica of the Black Butterfly, I don't know what I'm doing wrong but when I drag and drop the txt extracted from the bin file to repack it, it shows me this error:
Error: Could not find any instructions for "SaveNg"! Please check line 2 in the source file.

I didn't even modify any of the dialogues inside the txt.

**Comment by thesupersonic16** [comment]
I haven't worked on DALTools in a long time, maybe this will work.
[STSCTool.zip](https://github.com/user-attachments/files/19173806/STSCTool.zip)

**Comment by Linsey2244** [comment]
> I haven't worked on DALTools in a long time, maybe this will work. [STSCTool.zip](https://github.com/user-attachments/files/19173806/STSCTool.zip)

Thank you for the quick reply, I tried that one and when dragging and dropping the txt it shows me a different error from before. I have attached the bin files and two txt files in case they're useful:

Unhandled exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
 at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
 at System.Collections.Generic.List`1.get_Item(Int32 index)
 at STSCTool.STSCTextHandler.ConvertToObject(STSCFile file, String[] text)
 at STSCTool.Program.Main(String[] args)

[Script.zip](https://github.com/user-attachments/files/19182801/Script.zip)

[00_00_001.txt](https://github.com/user-attachments/files/19182843/00_00_001.txt)
[00_00_002.txt](https://github.com/user-attachments/files/19182844/00_00_002.txt)

**Comment by thesupersonic16** [comment]
This should work with 00_00_001.bin

You will need to recreate the txt files

[STSCTool.zip](https://github.com/user-attachments/files/19184268/STSCTool.zip)

**Comment by Linsey2244** [comment]
Thanks a lot! Now it's working perfectly. Do you have a Ko-fi or any other way to accept donations? I'd love to contribute a little as a token of appreciation for your work.

By the way, would it be possible to add support for zlib compression when generating the tex files for Pyschedelica of the Ashen Hawk and/or Pyschedelica of the Black Butterfly? (totally understand if it's not in your plans or if you're not interested) I translated the PNGs, but when I tried launching the game, I encountered this error:
---------------------------
Error
---------------------------
[Ver.1.00]
c:\project\kp\psy2_stm\prog\program\source\application\platform\windows\zlib\czlib.cpp
137
CZlib::Decode
Zlib Chunk error. 
---------------------------
Accept    
---------------------------

![Image](https://github.com/user-attachments/assets/7a446cab-96d7-4ad3-aedf-94b1e6585b62)

**Comment by Linsey2244** [comment]
These are the PNG and XML files I get when extracting the original TEX (attached in the ZIP along with the original TEX, the new uncompressed TEX, and the new compressed TEX).
I noticed that the XML file has <Compress>false</Compress>, so I tried changing it to <Compress>true</Compress> and then ran: `TEXTool -b BG20000.png BG20000.xml`

I placed the new TEX generated in the folder where all the TEX files were and repacked the PCK file (and placed the modified PCK file in the game folder). When I run the game, I get the following error:

**[Ver.1.00]
c:\project\kp\psy2_stm\prog\program\source\application\platform\windows\zlib\czlib.cpp
192
CZlib::Decode
Zlib inflate() error. -5 ???**

When I leave the <Compress>false</Compress> field as it is, a non-compressed TEX is generated, and when I run the game, I get the error mentioned in my previous message:

**[Ver.1.00]
c:\project\kp\psy2_stm\prog\program\source\application\platform\windows\zlib\czlib.cpp
137
CZlib::Decode
Zlib Chunk error.**

[Example.zip](https://github.com/user-attachments/files/19198826/Example.zip)

**Comment by thesupersonic16** [comment]
Does this load?
[BG20000.zip](https://github.com/user-attachments/files/19198914/BG20000.zip)

**Comment by Linsey2244** [comment]
I used your file and it's still showing this:
[Ver.1.00]
c:\project\kp\psy2_stm\prog\program\source\application\platform\windows\zlib\czlib.cpp
192
CZlib::Decode
Zlib inflate() error.  -5  ???

![Image](https://github.com/user-attachments/assets/700beeb1-3373-46ea-b55c-7475b17db72d)

**Comment by thesupersonic16** [comment]
Does this load?
[BG20000.zip](https://github.com/user-attachments/files/19199129/BG20000.zip)

**Comment by thesupersonic16** [comment]
oh forgot something.

**Comment by thesupersonic16** [comment]
Also try this.
[BG20000.zip](https://github.com/user-attachments/files/19199181/BG20000.zip)

**Comment by Linsey2244** [comment]
Still showing the same error sadly :(

![Image](https://github.com/user-attachments/assets/8cb87085-f406-4d0f-9a1f-75bbd4b592cd)

**Comment by thesupersonic16** [comment]
For both?

**Comment by Linsey2244** [comment]
Yep, same error for both of them

**Comment by thesupersonic16** [comment]
Try this.
[BG20000.zip](https://github.com/user-attachments/files/19199373/BG20000.zip)

**Comment by Linsey2244** [comment]
Same error 😥

**Comment by thesupersonic16** [comment]
Need to be sure this unedited tex file I am working with even works.
[BG20000.zip](https://github.com/user-attachments/files/19199413/BG20000.zip)

**Comment by Linsey2244** [comment]
Yeah that one works, I can attach more original tex files if you want, I don't know if it will be of any help tho

[BG.zip](https://github.com/user-attachments/files/19199455/BG.zip)

**Comment by thesupersonic16** [comment]
Does any of these two work? If not I am out of ideas.

[BG20000.zip](https://github.com/user-attachments/files/19199942/BG20000.zip)

[BG20000.zip](https://github.com/user-attachments/files/19199947/BG20000.zip)

**Comment by Linsey2244** [comment]
They don't :( it's a shame but thanks for trying to fix it

**Comment by thesupersonic16** [comment]
I actually have one more, which is no compression.
[BG20000.zip](https://github.com/user-attachments/files/19200019/BG20000.zip)

**Comment by Linsey2244** [comment]
Doesn't work either

**Comment by thesupersonic16** [comment]
Actually I once again got another.
[BG20000.zip](https://github.com/user-attachments/files/19200135/BG20000.zip)

**Comment by Linsey2244** [comment]
Omg, that one seems to be working!! (it has an image of a field instead of the prologue)

**Comment by thesupersonic16** [comment]
Not sure why multiple compressors for C# just cant compress in a way that the game likes it, while a python script can do it on my first try.

I have included a file `compress.py`. Create your tex like normal as **uncompressed**, then use the script to compress it by running a command like `python compress.py BG20000.tex`

[Release.zip](https://github.com/user-attachments/files/19200232/Release.zip)

**Comment by Linsey2244** [comment]
Thank you so much really! 😆
