### ISSUE TITLE
Freezing occurs when the script is inserted by modifying it to a po file.

### ISSUE THREAD

**Issue by shun9092** [thesupersonic16/DALTools#35]
I'm translating the game anew.
Still appreciating this tool.
When extracted, modified, and inserted as a po file, the game frees up.
I modified this file
'七罪は態度からだと分かりにくいが、
色々と手伝おうとしてくれているようだ。
そつなくこなしているので心配しなくてよさそうだな。'
Freaking occurs in this part and next.
The file below is the file I modified in Korean.
https://drive.google.com/file/d/1JxhR9WTeE0xncliYP7DUIrUbIbrEbFK-/view?usp=sharing
I'll be waiting for your answer. Thank you.

**Comment by thesupersonic16** [comment]
A freezing bug was fixed a couple of weeks ago. However if you started editing before the 11th of September you will need to update DALTools and reimport the translations in a fresh Script.pck.

Let me know if it still freezes after doing that.

**Comment by shun9092** [comment]
Freezing doesn't seem to have happened and has been fixed.
I want to build a project, but I can't build it.
I would appreciate it if you could let me know if there are any other options you need to build.
And the table editor is still not running.

**Comment by thesupersonic16** [comment]
GitHub Actions is not copying libraries, I will have to fix that.

**Comment by thesupersonic16** [comment]
Just pushed dc4c1a1a6d7999a3edcbcc7b36a7a2fce26d9d9d which instructs GitHub Actions to include the missing libraries. You can download the build using the same link I have sent before.

As for how to build, you will need to install Visual Studio 2022 (Not Visual Studio Code), and select to install .NET development.

**Comment by thesupersonic16** [comment]
Did you have `PropertyTools.dll` and `PropertyTools.Wpf.dll` in the same folder as the exe?

**Comment by shun9092** [comment]
![image](https://github.com/user-attachments/assets/4b2e2698-293c-4b35-9983-a53a8e141c00)

**Comment by thesupersonic16** [comment]
Try redownloading the file from [here](https://nightly.link/thesupersonic16/DALTools/workflows/build/master/DALTools-Release.zip).

Should look like this 
![image](https://github.com/user-attachments/assets/0253eaf1-2e2b-4786-bcad-8be6b16ce2d7)

**Comment by shun9092** [comment]
It does work well. Thank you!

**Comment by shun9092** [comment]
![image](https://github.com/user-attachments/assets/139366a7-b677-4a21-a0d0-5dcccb2ac4ef)

Is it possible to modify this table data as well?
This program doesn't support newline.
I wonder if it is possible to modify the newline change so that it can be changed.
And I think it's too difficult because I think I have to modify it in the program.
Likewise, I wonder if it is possible to extract it as a file that can be csv or several modifications.

**Comment by shun9092** [comment]
![image](https://github.com/user-attachments/assets/c4b2c80b-6a2e-455e-a488-22ed38578b52)

When I import the file, it is printed like this and it is so hard to edit.
You have to modify the cell while adjusting the size.
Then, if you make a mistake, the cells become smaller or initialized again, making it very difficult to modify.

**Comment by thesupersonic16** [comment]
Pushed b04c82aa32204d4c14222f07c1753baa0d2fa3fa to add import and exporting for TableEditor.

**Comment by shun9092** [comment]
Sorry, I don't know how to do that...

**Comment by thesupersonic16** [comment]
Make sure you are editing the "Translation" row while keeping "Key" untouched.

**Comment by shun9092** [comment]
Can you build it so that it can be downloaded?

**Comment by thesupersonic16** [comment]
Just edit the "Translation" column, like this. It will be empty when you export the file.
![image](https://github.com/user-attachments/assets/55200ed6-7cb4-4b19-951b-85055ae5f0e5)

**Comment by shun9092** [comment]
아니다. 내가 말한 부분은 테이블 에디터에 관한 내용이다.

Pushed 'b04c82a' to add import and exporting for TableEditor.

이 부분이다. 오류가 일어나서 빌드를 할 수 없기 때문이다.

**Comment by shun9092** [comment]
@thesupersonic16
On the first day, when I choose the Toka route at Ryzen High School, I get freesing and the game stops.
![image](https://github.com/user-attachments/assets/d3dda2a2-d315-4dfe-a435-658462941471)
https://drive.google.com/file/d/1d6ESBPxUQSmGzLWwwnBRAA3LPZp4E6zJ/view?usp=sharing
This is a save file and a script file that I have currently modified.
Please check the cause of the stop.

**Comment by thesupersonic16** [comment]
Just checked 001_01_05.bin, it contained an instruction I have defined incorrectly. Should be fixed in f31f83a99cf84f2a4a94ab17a8c534f308fa8ce6. You can download it from [GitHub Actions](https://nightly.link/thesupersonic16/DALTools/workflows/build/master/DALTools-Release.zip).

Since this is an issue with the instruction defination, you will need to reimport your translation in a clean Script.pck as your current one is now corrupted.

**Comment by shun9092** [comment]
It work well, thank you.
I will tell you if there is a problem in progress. Thank you.

**Comment by shun9092** [comment]
App Info:
```
    Version: 1.0.0
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\DATE A LIVE Ren Dystopia\Data\KOR\DALTools-Release\
    Process Level: User
```

Exception:
```
    Type: IndexOutOfRangeException
    Message: Index was outside the bounds of the array.
    Source: DALLib
    Function: Void Save(DALLib.IO.ExtendedBinaryWriter)
    StackTrace: 
       at DALLib.File.TableFile.Save(ExtendedBinaryWriter writer)
       at DALLib.File.FileBase.Save(Stream stream)
       at TableEditor.MainWindow.SaveTable(String path)
       at TableEditor.MainWindow.SaveButton_Click(Object sender, RoutedEventArgs e)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
       at System.Windows.Controls.Primitives.ButtonBase.OnClick()
       at System.Windows.Controls.Button.OnClick()
       at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
       at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
       at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
       at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
       at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
       at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
       at System.Windows.Input.InputManager.ProcessStagingArea()
       at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
       at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
       at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
       at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at System.Windows.Application.Run(Window window)
       at TableEditor.App.Main(String[] args)
    InnerException: 
```

TableEditor fatal error.
https://drive.google.com/file/d/1_O8AQRzlyik33vAtTvbZkpoyMVsLlY8c/view?usp=sharing
I tried to Import translation this file

**Comment by thesupersonic16** [comment]
The parser was not handling EOF properly, should now be fixed in a18391d8510fb17d3d80db4948cc00009a55b4e9.

**Comment by shun9092** [comment]
![image](https://github.com/user-attachments/assets/01afeac4-52fc-4a2b-9698-28db1dd99a46)
Unable to translate the choice of the character in the script, it does not appear to be extracted from the script.

**Comment by thesupersonic16** [comment]
What script file is this?

**Comment by thesupersonic16** [comment]
How did you get the crash? Just after double clicking?

**Comment by shun9092** [comment]
Right. It's an error that happens when I double-click to fix it.
And I extracted it as a po file.

**Comment by thesupersonic16** [comment]
Should now be fixed in 1c4da1f27d6bab3a9d443d40253d5c1dc35e9111.

I was unable to get the crash myself, will need more information or a video of you causing it. Anyways choices should now be exportable.

**Comment by shun9092** [comment]
![image](https://github.com/user-attachments/assets/373f04e8-f002-48cb-99fe-402042aedddb)
And I can't open the start02.bin file.
![image](https://github.com/user-attachments/assets/aa3ce74e-2f14-4ab8-aae0-924bfa2fc41d)
![image](https://github.com/user-attachments/assets/2104feb4-ecd9-4c12-8251-241e6b04d898)
Also, I have to translate the map name on the map selection screen, but I can't see this part either.

**Comment by shun9092** [comment]
SDE Info:
```
    Version: 1.1.0
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\DATE A LIVE Ren Dystopia\Data\KOR\
    Process Level: User
    ScriptPath: C:\Program Files (x86)\Steam\steamapps\common\DATE A LIVE Ren Dystopia\Data\JPN\Script\Script_ori.pck
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: ScriptDialogueEditor
    Function: Void CodeListView_MouseDoubleClick(System.Object, System.Windows.Input.MouseButtonEventArgs)
    StackTrace: 
       at ScriptDialogueEditor.MainWindow.CodeListView_MouseDoubleClick(Object sender, MouseButtonEventArgs e)
       at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
       at System.Windows.Controls.Control.OnMouseDoubleClick(MouseButtonEventArgs e)
       at System.Windows.Controls.Control.HandleDoubleClick(Object sender, MouseButtonEventArgs e)
       at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
       at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
       at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
       at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
       at System.Windows.Input.InputManager.ProcessStagingArea()
       at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
       at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
       at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
       at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at System.Windows.Application.Run(Window window)
       at ScriptDialogueEditor.App.Main(String[] args)
    InnerException: 
```

Still error happend.

**Comment by thesupersonic16** [comment]
When I last looked at start2.bin it looked like a script file but with minor differences, likely using an older version of the scripting engine.

As for the crash, I tried what you did and still could not reproduce the crash. Does it also happen on normal messages?

As for MapPlace text, should now be added in 94753d728798a8f34f9e406bb52ca1bcf4c726a2.

**Comment by shun9092** [comment]
It doesn't happen in other common scripts, it happens when you double click to modify character's choice options.

![image](https://github.com/user-attachments/assets/b0af132a-5c24-4c7c-bb9a-fad49b5d14d8)
![image](https://github.com/user-attachments/assets/ba3baa03-9a28-4429-af29-de9009d65ab5)
Also, I have to translate the map name on the map selection screen, but I can't see this.
Where is a MapName script?? I can't find script about that.

**Comment by thesupersonic16** [comment]
They might be textures. Nothing stands out to me besides MapPlace. Maybe check Data\Map.

**Comment by shun9092** [comment]
Ok, I found it! Thank you! That is textures. but choice is still happen by double click..

**Comment by shun9092** [comment]
If so, is start2.bin a file that doesn't have a script and doesn't need to be modified?

**Comment by thesupersonic16** [comment]
I am not sure where in the function the issue is, I can try making a build for you so that it can show line numbers.
[Release.zip](https://github.com/user-attachments/files/17298316/Release.zip)


No need to edit start2.bin as I don't think it gets loaded in game.

**Comment by shun9092** [comment]
![image](https://github.com/user-attachments/assets/010bc074-3281-4e55-a716-a2f9d2702976)
Name error

**Comment by shun9092** [comment]
![image](https://github.com/user-attachments/assets/c276cfaa-919c-4fac-93a6-227044ab3cc0)
![image](https://github.com/user-attachments/assets/f087d27f-8e66-4522-b358-2a8de68121a7)

I modified the file 'data_chara.bin'. By the way, the name here has not been modified. I don't know if I need to modify other parts. Or I don't know if there is any part where the name part hasn't been extracted.

**Comment by thesupersonic16** [comment]
Check `data_chara_voice.bin`

![image](https://github.com/user-attachments/assets/cd6f5200-b8b2-4ebf-b83a-cc96f00a573f)
![image](https://github.com/user-attachments/assets/874ac846-6848-4f68-9827-700ad25d316f)

**Comment by shun9092** [comment]
What's the difference between name1 and name2? Is there a difference between the parts used in the same name?

**Comment by thesupersonic16** [comment]
I believe in one of the games some characters can be given a non-spoiler name and a spoiler name. Though in this there might not be one.

**Comment by shun9092** [comment]
[title-eidted.zip](https://github.com/user-attachments/files/17529959/title-eidted.zip)

When I edit and insert the image, sometimes it doesn't run and doesn't return to the main screen.
I can't go into two days if I run it for the first time when I changed the title.

**Comment by thesupersonic16** [comment]
Is something wrong with this?

**Comment by shun9092** [comment]
I edited 'title.tex' and changed file. Sometimes the screen stops. I can't go back to the main screen.

**Comment by thesupersonic16** [comment]
Seems to work fine for me.

**Comment by shun9092** [comment]
https://github.com/user-attachments/assets/3d887f7b-89b9-4ed1-8720-e229079db278

I edited 'title.tex' and changed file. Sometimes the screen stops. I can't go back to the main screen.

**Comment by thesupersonic16** [comment]
I am not seeing the issue on my end. Maybe you edited something else that is causing the issue?

**Comment by shun9092** [comment]
If I use the original file, it works with no problem at all. However, if I use the modified file, sometimes it doesn't run.

**Comment by thesupersonic16** [comment]
File looks fine to me, and I still don't see any of the freezing issues you had. Try your tex without other edited files and see if it fixes itself.

**Comment by shun9092** [comment]
![image](https://github.com/user-attachments/assets/ea381596-6ca0-45b7-bdff-d097093d290f)
I can't find the script on the settings screen of keyboard settings. Do you know where I can change the script?

**Comment by thesupersonic16** [comment]
Those might be in the exe itself.

**Comment by Choviics** [comment]
Sorry to butt into the conversation but how can I download the latest version of the tools? I tried to go to GitHub Actions but it says link error

**Comment by thesupersonic16** [comment]
The files were expired, I just got them regenerated.

**Comment by shun9092** [comment]
Error incoming by Textool.exe, image file edited photoshop

Building Files detected, Building...
WARNING: No Frame Data was found! Please Extract it using the -i switch.

처리되지 않은 예외: System.AccessViolationException: 보호된 메모리를 읽거나 쓰려고 했습니다. 대부분 이러한 경우는 다른  메모리가 손상되었음을 나타냅니다.
   위치: System.Runtime.InteropServices.Marshal.CopyToManaged(IntPtr source, Object destination, Int32 startIndex, Int32 length)
   위치: DALLib.Imaging.ImageTools.LoadImage(String path, Int32& width, Int32& height, Byte[]& data)
   위치: TEXTool.Program.BuildTEX(TEXFile& tex, String name)
   위치: TEXTool.Program.Main(String[] args)


https://drive.google.com/file/d/1q5bo7L-SievouEdeTfSQq3O3lq4JWTyt/view?usp=sharing
